### PR TITLE
Add footprint model for DIP-32_W7.62

### PR DESCRIPTION
**Pull request by patricklaf**
Package used by UM61512AK SRAM and may be others components.

### CODE REVIEW

**Comment by Shackmeister** [comment]
You should add ${KISYS3DMOD}/ to your 3D model path. Either from the footprint editor or through a texteditor

**Comment by Shackmeister** [comment]
Another good habit for any PR is to add a Screenshot :)

**Comment by patricklaf** [comment]
image

**Comment by Shackmeister** [comment]
Merged
Thank you for your contribution

**Pull request merged**
