### PR TITLE
renamed DIP..._SMD to SMDIP... and added several more of these footprints

### PR DESCRIPTION
**Pull request by jkriege2**
As discussed there: https://github.com/KiCad/Housings_DIP.pretty/issues/12
I reworked the DIP..._SMD-footprints by renaming them to SMDIP... 
Also I added several footprints that were missing from this series. 

**Note:** 3D models have just been merged there (https://github.com/KiCad/kicad-library/pull/1651), but with the old name, so I added the old name to the footprints for now. If @Misca1234 can do a quick naming-fix for these, I'm happy to change the 3D-model-link before we merge ... Should we do the name change in a separate PR or here?

In addition I moved the silkscreen further away from the pads (see last image at the bottom)!

@evanshultz @Misca1234  @SchrodingersGat @poeschlr @hackscribble @slowcoder What do you all think? 

- script for these footprints: https://github.com/pointhi/kicad-footprint-generator/pull/58
- change of footprint-links in existing symbols: https://github.com/KiCad/kicad-library/pull/1655

Best,
JAN

PS: The scripts seem to crash for no obvious reason ... if I run our check's locally, there are the warnings about 3D model reference (see above) but no further errors ...

2017-09-24 11_22_23-3d viewer
2017-09-24 11_22_10-pcbnew d__kicad_kicad_review-project2_kicad_review-project2 kicad_pcb
2017-09-24 12_11_04-3d viewer

### CODE REVIEW

**Comment by jkriege2** [comment]
@Misca1234: Could you redo the 3D models with the correct names? I will open a PR for the name change as soon as you're ready (and this is merged ... or I can still do it here). When doing that, could you modify the models in one respect please: The DIP-packages are only available in a few package widths (as far as I know): 6.35mm, 9.14mm, 14.73mm, 22.35mm, 24.89mm When the pnrow-distance is wider than the "usual" width for that package, that means that the pins are bent to the outside, not so much the package! Could you implement that (somwhow) in the 3D models instead of simply making the black housing wider?

see e.g. https://www.vishay.com/docs/83606/cny17.pdf

Thanks,
JAN

**Comment by SchrodingersGat** [comment]
Yep please fix the associated naming for the 3D model within each footprint and @Misca1234 if you can fix the naming of the actual models that would be great

**Comment by jkriege2** [comment]
Done from my side ...

JAN

**Comment by Misca1234** [comment]
I am on it, I fix the scripts but not make a push of the actual models ?

**Comment by Misca1234** [comment]
Shall i create all SMD models for all distances and npins from 4 to 64 ?

I have only added those widths and pins that existe in pretty repository that did not habe long/short pads in their name
For example, the script only generate the model for SMDIP-48_W15.24mm

**Comment by Misca1234** [comment]
I can modify the measurements a little bit,
is it something like this yo uwant (This is the eample you highlighted above, (oldname) DIP-4_W9.53mm_SMD)


bild

**Comment by jkriege2** [comment]
Having as many models as possible would be good ... The LargePad-variants you don't need to make ... I'll modify those footprints (will post a PR later this week) that links the base model.

I think the DIP-4_W9.53mm_SMD is the default ... it's the >=10.16mm pitch SMD and THT-models, where the package has the same width as above, but the pins are bent to fit the wider pin-column distance (see the 10.16mm THT-variant that I linked as DS above)

**Comment by Misca1234** [comment]
The wider ones get a little spider like if they should adapt to the silk square

Making the legs tilt 45 degree or so could be a solution but that need some re work

bild

**Comment by Misca1234** [comment]
Do we want the spider variant or the one where the body is a little thicker in case I dont sort out pins that is angled ?

**Comment by jkriege2** [comment]
I think spider-like is fine for illustration (the body size is the most important feature IMHO), but angled legs would be the ultimate solution. See this DS http://www.farnell.com/datasheets/73758.pdf for an example of such a package

**Comment by jkriege2** [comment]
PS: I made a PR reducing the number of required 3D model variants: https://github.com/KiCad/Housings_DIP.pretty/pull/17

**Comment by Misca1234** [comment]
Ok, i do the spider and match the sd models in the latest pretty push, give me an hour or so

**Pull request merged**
