### PR TITLE
Added Sony_DIP-22_15.1x18.0_W15.24mm_Pitch1.27mm

### PR DESCRIPTION
**Pull request by Misca1234**
I am a little uncertain of this one

Currently I am overhauling the video.lib and encountered the chip 
ICX415AQ
http://www.datasheet4u.com/download_new.php?id=571963

Which have specific 22-DIP foot print.

In this push I created it with the name 
DIP-22_W15.24mm_Pitch1.27mm.kicad_mod

bild

Should this be it's correct name ?

### CODE REVIEW

**Comment by poeschlr** [comment]
I would include the body size for this footprint. It looks like it has a non standard body.  (Normally the body would not be that wide.)

From: https://github.com/KiCad/kicad-library/issues/1447
> ### Through Hole (DIP, ...)
> `{[Manufacturer name]_}[package name]-[pin count]{_[Size x]x[Size y]{x[Height]}mm}_W[Lead Span]mm_Pitch[pin pitch]mm{_Lead[Lead Width]mm}{_Pad[pad length]{x[pad width]}}{_footprint options}`
> 
> - For THT packages the main identifying dimension is the `lead span`. (Compared to the use of Body size in SMD components.)
> - Body dimensions are optional for this type of footprint.
> - The optional parameter `lead width` describes the nominal dimension for which the footprint is designed.

---

I think here a chamfer for pin 1 marker woud be more appropriate. (And L style for the silk layer)
29751772-6f6df106-8b52-11e7-9383-1a61387eab23

---

Note: i did not yet check the file. I only looked at the screenshot.

**Comment by SchrodingersGat** [comment]
Also the shape of pin-1 should be changed to rectangular (all others should remain circular)

**Comment by Misca1234** [comment]
Changed into this (Shall I add the suffix THT as well ?)


bild


I have this 3D model ready to be push when this foot print is in

bild

**Comment by poeschlr** [comment]
I would still suggest to add the body size. Sony might have other parts with similar packages but different body size.

**Comment by Misca1234** [comment]
Renamed into this 

bild

**Comment by SchrodingersGat** [comment]
@Misca1234 

In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
