### PR TITLE
Add DIP-8_W10.9mm_SMD to support ACPL-7900 gull wing

### PR DESCRIPTION
**Pull request by rasilon**

### CODE REVIEW

**Comment by jkriege2** [comment]
Hi!

I pressume this is supposed to match the sketch in https://docs.broadcom.com/cs/Satellite?blobcol=urldata&blobheader=application%2Fpdf&blobheadername1=Content-Disposition&blobheadername2=Content-Type&blobheadername3=MDT-Type&blobheadervalue1=attachment%3Bfilename%3Dpub-005417_DS_ACPL-790x_2016-07-19.pdf&blobheadervalue2=application%2Fx-download&blobheadervalue3=abinary%253B%2Bcharset%253DUTF-8&blobkey=id&blobnocache=true&blobtable=MungoBlobs&blobwhere=1430874891930&ssbinary=true ... and should be used together with https://github.com/KiCad/kicad-library/pull/1538 correct? 

As I understand this is a manufacturer-specific symbol, I would propose to rename it to `Avago_DIP-8_W10.9mm_SMD` (they don't seem to have a specific name for that package, if you find one, please put it into the name in the form `MANUFACTURER_MPN`).

The pads seem to be too far outside .. the DS shows an over-pad-width of 10.9mm and an inner distance between the pads of 10.9mm-2*2.0mm=6.9mm.

Please change the symbol as suggested and have another look at the existing `DIP-8_W9.53mm_SMD` footprint ... maybe that one is OK for such devices? If not I'm happy to merge the corrected new FP!

Also: Please add a 3D model link, although the model does not exist (yet). This way the 3D model is used, as soon as somebody proviedes it (which would not happen if the link is not there!)

Best,
JAN

**Comment by jkriege2** [comment]
... and please correct the courtyard clearance. It should be 0.25mm al around the symbol (seems to be way too large on the left/right)!

Thanks,
JAN

PS: In future please add a screenshot and some description (including datasheet and linsk to PRs where thos should be used, if they exist), as this makes review much easier!

**Comment by rasilon** [comment]
Hi,
That's correct, yes.  I've renamed it, and adjusted the courtyard and the pad sizes.  There are a number of pads that work for that package; this one, plus DIP-8_W9.53mm_SMD as you suggested, and DIP-8_W7.62mm_SMD, which I ended up using and hand solders reasonably well.  I've added the model link, using that name, and added the matching model to [KiCad/kicad-library#1538](https://github.com/KiCad/kicad-library/pull/1538)

Thanks,
Derry

**Comment by jkriege2** [comment]
Hi the courtyard on the left/right is still too close to the pads ... distance from border of the pad to the courtyard-line (= clearance) should be 0.25mm, but it's more 0.2mm in your footprints.

Best,
JAN

**Comment by SchrodingersGat** [comment]
@rasilon 



In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
